name: Docker Build and Push to DockerHub

on:
  push:
    branches:
      - main
    paths:
      - "backend/Dockerfile"
      - "frontend/Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build ./backend/ -t surajkumar00/chattychan-backend:latest
          docker build ./frontend/ -t surajkumar00/chattychan-frontend:latest

      - name: Push Docker image to DockerHub
        run: |
          docker push surajkumar00/chattychan-backend:latest
          docker push surajkumar00/chattychan-frontend:latest
